# Generated by Django 2.0.5 on 2018-05-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Openlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
